// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class Commodity
{
    public int CommodityId { get; set; }

    public int NmvntaskId { get; set; }

    public string Code { get; set; }

    public string OfficialCode { get; set; }

    public string CodePartA { get; set; }

    public string CodePartB { get; set; }

    public string CodePartC { get; set; }

    public string CodePartD { get; set; }

    public string CodePartE { get; set; }

    public string CodePartF { get; set; }

    public string Name { get; set; }

    public string OfficialName { get; set; }

    public string OriginalName { get; set; }

    public string CartonCode { get; set; }

    public int? PreviousCommodityId { get; set; }

    public int? RecycleCommodityId { get; set; }

    public int CommodityBrandId { get; set; }

    public int CommodityCategoryId { get; set; }

    public int CommodityTypeId { get; set; }

    public int CommodityClassId { get; set; }

    public int CommodityLineId { get; set; }

    public int? CommoditySizeId { get; set; }

    public int? CommodityCoreId { get; set; }

    public int? CommoditySkinId { get; set; }

    public int? CommodityIconId { get; set; }

    public int SupplierId { get; set; }

    public int UserId { get; set; }

    public int PreparedPersonId { get; set; }

    public int OrganizationalUnitId { get; set; }

    public int LocationId { get; set; }

    public decimal PiecePerPack { get; set; }

    public decimal PackPerPallet { get; set; }

    public decimal QuantityAlert { get; set; }

    public decimal ListedPrice { get; set; }

    public decimal GrossPrice { get; set; }

    public string PurchaseUnit { get; set; }

    public string SalesUnit { get; set; }

    public string Packing { get; set; }

    public string Origin { get; set; }

    public decimal? WeightBase { get; set; }

    public decimal? WeightPercent { get; set; }

    public decimal? Weight { get; set; }

    public decimal? TareWeight { get; set; }

    public decimal Volume { get; set; }

    public decimal PackageVolume { get; set; }

    public int Shelflife { get; set; }

    public int Shelflifeday { get; set; }

    public int? LeadTime { get; set; }

    public string Hscode { get; set; }

    public bool IsAssembly { get; set; }

    public bool IsRegularCheckUps { get; set; }

    public bool Discontinue { get; set; }

    public string BaseUrl { get; set; }

    public string Caption { get; set; }

    public string Specification { get; set; }

    public string Description { get; set; }

    public string Remarks { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime EditedDate { get; set; }

    public bool InActive { get; set; }

    public virtual ICollection<Commodity> InverseRecycleCommodity { get; set; } = new List<Commodity>();

    public virtual Commodity RecycleCommodity { get; set; }

    public virtual User User { get; set; }
}