// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class Location
{
    public int LocationId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string OfficialName { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }

    public string Facsimile { get; set; }

    public string Remarks { get; set; }

    public DateTime LockedDate { get; set; }

    public string AspUserId { get; set; }

    public DateTime EditedDate { get; set; }

    public virtual ICollection<OrganizationalUnit> OrganizationalUnits { get; set; } = new List<OrganizationalUnit>();
}