// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class OrganizationalUnitUser
{
    public int OrganizationalUnitUserId { get; set; }

    public int OrganizationalUnitId { get; set; }

    public int UserId { get; set; }

    public bool InActive { get; set; }

    public DateTime? InActiveDate { get; set; }

    public virtual OrganizationalUnit OrganizationalUnit { get; set; }

    public virtual User User { get; set; }
}