// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class OrganizationalUnit
{
    public int OrganizationalUnitId { get; set; }

    public string Code { get; set; }

    public string OfficalCode { get; set; }

    public string Name { get; set; }

    public int LocationId { get; set; }

    public bool InActive { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<OrganizationalUnitUser> OrganizationalUnitUsers { get; set; } = new List<OrganizationalUnitUser>();
}