// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<Commodity> Commodities { get; set; } = new List<Commodity>();

    public virtual ICollection<OrganizationalUnitUser> OrganizationalUnitUsers { get; set; } = new List<OrganizationalUnitUser>();
}