// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int WarehouseCategoryId { get; set; }

    public int WarehouseGroupId { get; set; }

    public int WarehouseClassId { get; set; }

    public int CommodityTypeId { get; set; }

    public int LocationId { get; set; }

    public bool Bookable { get; set; }

    public bool Issuable { get; set; }

    public bool IsDefault { get; set; }

    public string Description { get; set; }

    public string Remarks { get; set; }

    public bool InActive { get; set; }

    public virtual WarehouseClass WarehouseClass { get; set; }

    public virtual WarehouseGroup WarehouseGroup { get; set; }
}