// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotalModel.Models;

public partial class WarehouseClass
{
    public int WarehouseClassId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Remarks { get; set; }

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}